//! Type checker implementation for the Opalescent type system

#![allow(
    clippy::multiple_inherent_impl,
    reason = "TypeChecker impl blocks intentionally split across submodules (checker/*.rs) for code organization - each submodule handles a specific aspect of type checking"
)]

extern crate alloc;

use super::constraints::TypeConstraint;
use super::environment::TypeEnvironment;
use super::errors::TypeError;
use super::substitution::Substitution;
use super::symbol_table::{SymbolInfo, SymbolTable};
use super::types::{CoreType, TypeVar};
use crate::ast::Type;
use crate::token::Span;
use alloc::{boxed::Box, format, string::String, vec::Vec};

// Sub-modules
mod declarations;
mod expressions;
mod helpers;
mod statements;
mod unification;

/// Core type checker responsible for validating and inferring types
/// throughout the Opalescent type system
pub struct TypeChecker {
    /// Current type environment
    environment: TypeEnvironment,
    /// Counter for generating fresh type variables
    next_var_id: usize,
    /// Symbol table for tracking symbols in scope (Phase 2 and Phase 6)
    symbol_table: SymbolTable,
    /// Collected type constraints for inference (Phase 2)
    constraints: Vec<TypeConstraint>,
}

impl TypeChecker {
    /// Create a new type checker with a fresh environment
    pub fn new() -> Self {
        Self {
            environment: TypeEnvironment::new(),
            next_var_id: 0,
            symbol_table: SymbolTable::new(),
            constraints: Vec::new(),
        }
    }

    /// Create a type checker with a specific environment
    pub fn with_environment(environment: TypeEnvironment) -> Self {
        Self {
            environment,
            next_var_id: 0,
            symbol_table: SymbolTable::new(),
            constraints: Vec::new(),
        }
    }

    /// Get a reference to the current environment
    pub const fn environment(&self) -> &TypeEnvironment {
        &self.environment
    }

    /// Get a mutable reference to the current environment
    #[expect(
        clippy::missing_const_for_fn,
        reason = "Cannot have const fn with mutable reference"
    )]
    pub fn environment_mut(&mut self) -> &mut TypeEnvironment {
        &mut self.environment
    }

    /// Get a reference to the symbol table
    pub const fn symbol_table(&self) -> &SymbolTable {
        &self.symbol_table
    }

    /// Get a mutable reference to the symbol table
    pub const fn symbol_table_mut(&mut self) -> &mut SymbolTable {
        &mut self.symbol_table
    }

    /// Register a symbol for ABI signature generation (Phase 6)
    pub fn register_symbol(&mut self, symbol: SymbolInfo) {
        self.symbol_table.register(symbol);
    }

    /// Add a type constraint for inference (Phase 2)
    pub fn add_constraint(&mut self, constraint: TypeConstraint) {
        self.constraints.push(constraint);
    }

    /// Get all collected constraints
    #[expect(
        clippy::missing_const_for_fn,
        reason = "Vec deref coercion to slice is not allowed in const fn"
    )]
    pub fn constraints(&self) -> &[TypeConstraint] {
        &self.constraints
    }

    /// Clear all collected constraints
    pub fn clear_constraints(&mut self) {
        self.constraints.clear();
    }

    /// Solve all collected constraints (Phase 2 - not yet implemented)
    ///
    /// This will be the main entry point for constraint-based type inference.
    /// It should unify all constraints and return a substitution that satisfies them all.
    ///
    /// # Span Integration Status
    ///
    /// This method attempts to provide precise source spans for all diagnostics. However,
    /// some constraints may have `None` spans when:
    /// - The constraint was generated by the compiler (not directly from user code)
    /// - The constraint originated from a synthesized type during inference
    /// - The constraint involves implicit conversions or compiler-generated code
    ///
    /// In these cases, `unknown_span()` is used as a fallback. The goal is to eliminate
    /// all `unknown_span()` usage by ensuring all constraints capture their originating
    /// source locations during AST traversal.
    ///
    /// TODO(Phase 2): Track and eliminate all remaining `unknown_span()` usage. Consider
    /// adding debug assertions in test builds to detect constraints with missing spans.
    ///
    /// # Errors
    ///
    /// Returns `TypeError::ConstraintSolvingFailed` if constraints cannot be satisfied.
    pub fn solve_constraints(&mut self) -> Result<Substitution, TypeError> {
        let pending_constraints = core::mem::take(&mut self.constraints);
        let mut substitution = Substitution::empty();

        for constraint in pending_constraints {
            match constraint {
                TypeConstraint::Equality {
                    left,
                    right,
                    left_span,
                    right_span,
                } => {
                    let left_applied = substitution.apply(&left);
                    let right_applied = substitution.apply(&right);
                    let constraint_subst =
                        self.unify(&left_applied, &right_applied, left_span, right_span)?;
                    substitution = substitution.compose(&constraint_subst);
                }
                TypeConstraint::HasField {
                    owner_span,
                    field_span,
                    ..
                } => {
                    // Prefer primary span, fall back to secondary, then unknown
                    // NOTE: HasField constraints should always have at least one span
                    let diagnostic_span = owner_span
                        .or(field_span)
                        .map_or_else(TypeError::unknown_span, TypeError::span_from_span);
                    return Err(TypeError::NotImplementedYet {
                        feature: "constraint type HasField".to_owned(),
                        span: diagnostic_span,
                    });
                }
                TypeConstraint::Callable {
                    callee,
                    arguments,
                    return_type,
                    callee_span,
                    argument_spans,
                    return_span,
                } => {
                    // Apply current substitution to callee type
                    let callee_applied = substitution.apply(&callee);

                    // Extract function signature from callee type
                    if let CoreType::Function {
                        parameters,
                        return_type: fn_return,
                        error_types: _fn_errors,
                    } = callee_applied
                    {
                        // Check arity (number of arguments)
                        if parameters.len() != arguments.len() {
                            let diagnostic_span = callee_span
                                .map_or_else(TypeError::unknown_span, TypeError::span_from_span);
                            return Err(TypeError::ArityMismatch {
                                expected: parameters.len(),
                                found: arguments.len(),
                                span: diagnostic_span,
                            });
                        }

                        // Unify each parameter with corresponding argument
                        for (i, (param_type, arg_type)) in
                            parameters.iter().zip(arguments.iter()).enumerate()
                        {
                            let param_applied = substitution.apply(param_type);
                            let arg_applied = substitution.apply(arg_type);
                            let arg_span = argument_spans.get(i).and_then(|s| *s).or(callee_span);
                            let param_subst =
                                self.unify(&param_applied, &arg_applied, None, arg_span)?;
                            substitution = substitution.compose(&param_subst);
                        }

                        // Unify return type
                        let fn_return_applied = substitution.apply(&fn_return);
                        let return_type_applied = substitution.apply(&return_type);
                        let return_subst = self.unify(
                            &fn_return_applied,
                            &return_type_applied,
                            callee_span,
                            return_span,
                        )?;
                        substitution = substitution.compose(&return_subst);
                    } else {
                        // Callee is not a function type
                        let diagnostic_span = callee_span
                            .map_or_else(TypeError::unknown_span, TypeError::span_from_span);
                        return Err(TypeError::NotCallable {
                            type_name: format!("{callee_applied}"),
                            span: diagnostic_span,
                        });
                    }
                }
            }
        }

        Ok(substitution)
    }

    /// Generate a fresh type variable
    ///
    /// # Arguments
    ///
    /// * `name` - Human-readable name for the type variable
    /// * `span` - Source location where the type variable is introduced (for error reporting)
    ///
    /// # Errors
    ///
    /// Returns `TypeError::ConstraintSolvingFailed` if type variable ID overflows
    pub fn fresh_type_var(&mut self, name: String, span: Span) -> Result<CoreType, TypeError> {
        let var = TypeVar::new(self.next_var_id, name);
        self.next_var_id =
            self.next_var_id
                .checked_add(1)
                .ok_or_else(|| TypeError::ConstraintSolvingFailed {
                    reason: "type variable counter overflow".to_owned(),
                    span: TypeError::span_from_span(span),
                })?;
        Ok(CoreType::Variable(var))
    }

    /// Generate a fresh type variable with an auto-generated name
    ///
    /// # Arguments
    ///
    /// * `span` - Source location where the type variable is introduced (for error reporting)
    ///
    /// # Errors
    ///
    /// Returns `TypeError::ConstraintSolvingFailed` if type variable ID overflows
    pub fn fresh_type_var_auto(&mut self, span: Span) -> Result<CoreType, TypeError> {
        self.fresh_type_var(format!("t{}", self.next_var_id), span)
    }

    /// Convert an AST Type to a `CoreType` for validation and instantiation
    /// Supports generics, arrays, and function types.
    ///
    /// # Errors
    ///
    /// Returns `TypeError` variants when type conversion fails
    pub fn ast_type_to_core_type(ast_type: &Type) -> Result<CoreType, TypeError> {
        match *ast_type {
            Type::Basic { ref name, span } => match name.as_str() {
                "int8" => Ok(CoreType::Int8),
                "int16" => Ok(CoreType::Int16),
                "int32" => Ok(CoreType::Int32),
                "int64" => Ok(CoreType::Int64),
                "uint8" => Ok(CoreType::UInt8),
                "uint16" => Ok(CoreType::UInt16),
                "uint32" => Ok(CoreType::UInt32),
                "uint64" => Ok(CoreType::UInt64),
                "float32" => Ok(CoreType::Float32),
                "float64" => Ok(CoreType::Float64),
                "string" => Ok(CoreType::String),
                "boolean" => Ok(CoreType::Boolean),
                "unit" => Ok(CoreType::Unit),
                _ => Err(TypeError::TypeNotFound {
                    type_name: name.clone(),
                    span: TypeError::span_from_span(span),
                }),
            },
            Type::Array {
                ref element_type, ..
            } => {
                let core_element = Self::ast_type_to_core_type(element_type.as_ref())?;
                Ok(CoreType::Array(Box::new(core_element)))
            }
            Type::Function {
                ref parameters,
                ref return_type,
                ..
            } => {
                let mut core_params = Vec::with_capacity(parameters.len());
                for param in parameters {
                    core_params.push(Self::ast_type_to_core_type(param)?);
                }
                let core_return = Self::ast_type_to_core_type(return_type.as_ref())?;
                // NOTE: Function type node may carry an errors clause for pretty-printing
                // and documentation. For conversion, we attempt to resolve these types; if a
                // type is unknown at this stage (e.g., custom ADT not yet declared), we map
                // it into a nominal `Generic { name, args: [] }` form to preserve intent
                // without failing conversion.
                let mut core_errors: Vec<CoreType> = Vec::new();
                if let Type::Function { ref errors, .. } = *ast_type {
                    if let Some(list) = errors.as_ref() {
                        for err_ty in list {
                            match Self::ast_type_to_core_type(err_ty) {
                                Ok(core) => core_errors.push(core),
                                Err(TypeError::TypeNotFound { type_name, .. }) => {
                                    core_errors.push(CoreType::Generic {
                                        name: type_name,
                                        type_args: Vec::new(),
                                    });
                                }
                                Err(other) => return Err(other),
                            }
                        }
                    }
                }

                Ok(CoreType::Function {
                    parameters: core_params,
                    return_type: Box::new(core_return),
                    error_types: core_errors,
                })
            }
            Type::Generic {
                ref name,
                ref type_args,
                ..
            } => {
                let mut core_args = Vec::with_capacity(type_args.len());
                for arg in type_args {
                    core_args.push(Self::ast_type_to_core_type(arg)?);
                }
                Ok(CoreType::Generic {
                    name: name.clone(),
                    type_args: core_args,
                })
            }
        }
    }

    /// Validate algebraic data type definitions against the known type environment to ensure all
    /// referenced field and variant types are resolvable.
    ///
    /// # Errors
    ///
    /// Returns `TypeError` variants when ADT validation fails
    pub fn validate_adt_type(type_def: &crate::ast::TypeDef) -> Result<(), TypeError> {
        match *type_def {
            crate::ast::TypeDef::Sum { ref variants, .. } => {
                for variant in variants {
                    for field in &variant.fields {
                        Self::ast_type_to_core_type(&field.type_annotation)?;
                    }
                }
            }
            crate::ast::TypeDef::Product { ref fields, .. } => {
                for field in fields {
                    Self::ast_type_to_core_type(&field.type_annotation)?;
                }
            }
            crate::ast::TypeDef::Alias {
                ref target_type, ..
            } => {
                Self::ast_type_to_core_type(target_type)?;
            }
        }
        Ok(())
    }

    /// Type check a pattern match expression
    /// Ensures all patterns and arms are type compatible
    ///
    /// # Errors
    ///
    /// Returns `TypeError` variants when pattern matching validation fails
    pub fn type_check_pattern_match(
        &self,
        matched_type: &CoreType,
        matched_span: Span,
        patterns: &[(CoreType, Span)],
        arm_types: &[(CoreType, Span)],
    ) -> Result<(), TypeError> {
        for pattern in patterns {
            let pattern_type = &pattern.0;
            let pattern_span = pattern.1;
            if !self.types_compatible(matched_type, pattern_type) {
                return Err(TypeError::TypeMismatch {
                    expected: matched_type.to_string(),
                    found: pattern_type.to_string(),
                    found_span: TypeError::span_from_span(pattern_span),
                    expected_span: Some(TypeError::span_from_span(matched_span)),
                });
            }
        }

        if let Some(first) = arm_types.first() {
            let first_type = &first.0;
            let first_span = first.1;
            for arm in arm_types {
                let arm_type = &arm.0;
                let arm_span = arm.1;
                if !self.types_compatible(first_type, arm_type) {
                    return Err(TypeError::TypeMismatch {
                        expected: first_type.to_string(),
                        found: arm_type.to_string(),
                        found_span: TypeError::span_from_span(arm_span),
                        expected_span: Some(TypeError::span_from_span(first_span)),
                    });
                }
            }
        }

        Ok(())
    }

    /// Check if two core types are structurally compatible (including nested types)
    ///
    /// This method performs deep structural comparison for complex types like
    /// arrays, functions, and generics, ensuring all nested components are compatible.
    /// For simple equality checking, use the `==` operator on `CoreType` directly.
    #[expect(
        clippy::only_used_in_recursion,
        reason = "self parameter needed for structural recursion"
    )]
    pub fn types_compatible(&self, left: &CoreType, right: &CoreType) -> bool {
        // Clone to owned values to allow safe pattern matching without moving out of borrows.
        // This trades some performance for clarity and lint compliance; core types are small.
        let l = left.clone();
        let r = right.clone();
        match (l, r) {
            // All primitive types
            (CoreType::Int8, CoreType::Int8)
            | (CoreType::Int16, CoreType::Int16)
            | (CoreType::Int32, CoreType::Int32)
            | (CoreType::Int64, CoreType::Int64)
            | (CoreType::UInt8, CoreType::UInt8)
            | (CoreType::UInt16, CoreType::UInt16)
            | (CoreType::UInt32, CoreType::UInt32)
            | (CoreType::UInt64, CoreType::UInt64)
            | (CoreType::Float32, CoreType::Float32)
            | (CoreType::Float64, CoreType::Float64)
            | (CoreType::Boolean, CoreType::Boolean)
            | (CoreType::String, CoreType::String)
            | (CoreType::Unit, CoreType::Unit) => true,

            // Type variables are compatible with themselves
            (CoreType::Variable(var1), CoreType::Variable(var2)) => var1.id == var2.id,

            // Arrays are compatible if their element types are compatible
            (CoreType::Array(left_elem), CoreType::Array(right_elem)) => {
                self.types_compatible(left_elem.as_ref(), right_elem.as_ref())
            }

            // Functions are compatible if parameters and return types are compatible
            (
                CoreType::Function {
                    parameters: left_params,
                    return_type: left_ret,
                    error_types: left_errors,
                },
                CoreType::Function {
                    parameters: right_params,
                    return_type: right_ret,
                    error_types: right_errors,
                },
            ) => {
                if left_params.len() != right_params.len() {
                    return false;
                }
                for (left_param, right_param) in left_params.iter().zip(right_params.iter()) {
                    if !self.types_compatible(left_param, right_param) {
                        return false;
                    }
                }
                if !self.types_compatible(left_ret.as_ref(), right_ret.as_ref()) {
                    return false;
                }
                if left_errors.len() != right_errors.len() {
                    return false;
                }
                for (le, re) in left_errors.iter().zip(right_errors.iter()) {
                    if !self.types_compatible(le, re) {
                        return false;
                    }
                }
                true
            }

            // Generic types are compatible if names and type arguments match
            (
                CoreType::Generic {
                    name: left_name,
                    type_args: left_args,
                },
                CoreType::Generic {
                    name: right_name,
                    type_args: right_args,
                },
            ) => {
                if left_name != right_name || left_args.len() != right_args.len() {
                    return false;
                }
                for (left_arg, right_arg) in left_args.iter().zip(right_args.iter()) {
                    if !self.types_compatible(left_arg, right_arg) {
                        return false;
                    }
                }
                true
            }

            // Different types are not compatible
            _ => false,
        }
    }

    /// Validate a cast expression and classify it as safe or unsafe.
    ///
    /// See [`is_safe_cast`](super::checker::helpers::is_safe_cast) for detailed cast safety rules.
    ///
    /// # Cast Safety Categories
    ///
    /// - **Safe (widening)**: Returns `Ok(())` - no data loss possible
    /// - **Unsafe (narrowing)**: Returns `Err(UnsafeCast)` - may lose data,
    ///   runtime trap in debug mode per language spec (math.md)
    /// - **Invalid**: Returns `Err(InvalidCast)` - not allowed (non-numeric types)
    ///
    /// # Overflow Behavior (per language spec)
    ///
    /// Unsafe casts follow the arithmetic overflow rules from math.md:
    /// - **Debug mode**: Runtime trap on overflow/out-of-range values
    /// - **Release mode**: Wrapping behavior (no trap)
    /// - **Compile-time**: Overflow detection for constant expressions (future)
    ///
    /// # Errors
    ///
    /// Returns `TypeError::InvalidCast` if the cast is not valid (non-numeric types).
    /// Returns `TypeError::UnsafeCast` if the cast may lose data (narrowing conversion).
    ///
    /// # Future Work
    ///
    /// - TODO(Phase 2): Convert `UnsafeCast` errors to warnings when warning system exists
    /// - TODO(Phase 5): Generate runtime traps for debug builds
    /// - TODO(Phase 5): Implement compile-time overflow detection for constants
    pub fn validate_cast(
        from_type: &CoreType,
        to_type: &CoreType,
        span: Span,
    ) -> Result<(), TypeError> {
        use super::checker::helpers::{is_safe_cast, is_valid_cast};

        // Check if the cast is valid at all
        if !is_valid_cast(from_type, to_type) {
            return Err(TypeError::InvalidCast {
                from_type: from_type.to_string(),
                to_type: to_type.to_string(),
                span: TypeError::span_from_span(span),
            });
        }

        // Check if the cast is safe (widening) or unsafe (narrowing)
        // Emit error for unsafe casts now; in Phase 2 these will become warnings
        if !is_safe_cast(from_type, to_type) {
            return Err(TypeError::UnsafeCast {
                from_type: from_type.to_string(),
                to_type: to_type.to_string(),
                span: TypeError::span_from_span(span),
            });
        }

        Ok(())
    }

    /// Execute a closure within a fresh lexical scope, ensuring the scope is
    /// entered and exited even when the closure returns early.
    pub(super) fn within_new_scope<F, R>(&mut self, action: F) -> R
    where
        F: FnOnce(&mut Self) -> R,
    {
        self.symbol_table.enter_scope();
        let result = action(self);
        self.symbol_table.exit_scope();
        result
    }
}

impl Default for TypeChecker {
    fn default() -> Self {
        Self::new()
    }
}
