use super::StdlibErrorFamily;

#[rustfmt::skip]
/// Canonical and compatibility named error-set declarations.
pub(super) const STDLIB_ERROR_FAMILIES: &[StdlibErrorFamily] = &[
    // Canonical named error sets from `standard.errors`.
    StdlibErrorFamily { name: "ParseErrors", members: &["ParseError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "AllocationErrors", members: &["AllocationFailureError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "IndexAccessErrors", members: &["IndexOutOfBoundsError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ConstraintErrors", members: &["ConstraintViolationError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "BytesDecodeErrors", members: &["HexDecodeError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "BytesSliceErrors", members: &["SliceRangeError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "BytesErrors", members: &["HexDecodeError", "SliceRangeError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringSearchErrors", members: &["StringEmptySearchTextError", "StringPatternNotFoundError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringRangeErrors", members: &["StringNegativeCountError", "StringRangeOutOfBoundsError", "StringRangeOrderError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringMutationErrors", members: &["StringRangeOutOfBoundsError", "StringRangeOrderError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringSliceErrors", members: &["StringNegativeCountError", "StringRangeOutOfBoundsError", "StringRangeOrderError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringBuilderErrors", members: &["BuilderFinishedError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringJoinErrors", members: &["AllocationFailureError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalTextLayoutErrors", members: &["TerminalTextLayoutError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StringProcessingErrors", members: &["StringEmptySearchTextError", "StringPatternNotFoundError", "StringNegativeCountError", "StringRangeOutOfBoundsError", "StringRangeOrderError", "BuilderFinishedError", "AllocationFailureError", "TerminalTextLayoutError",], warning_eligible: false, specificity_rank: 2 },
    StdlibErrorFamily { name: "StandardInputErrors", members: &["StandardInputReadError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "StandardOutputAcquireErrors", members: &["StandardOutputHandleError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "StandardOutputCapabilityErrors", members: &["StandardOutputCapabilityError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "StdoutWriteErrors", members: &["WriteFailureError", "SinkClosedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StdoutFlushErrors", members: &["FlushFailureError", "SinkClosedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "StdoutWriterErrors", members: &["WriteFailureError", "FlushFailureError", "SinkClosedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalControlErrors", members: &["TerminalWriteFailureError", "InvalidCursorPositionError", "SinkClosedError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalDrawErrors", members: &["TerminalWriteFailureError", "SinkClosedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "RenderErrors", members: &["WriteFailureError", "FlushFailureError", "TerminalWriteFailureError", "InvalidCursorPositionError", "SinkClosedError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "RenderSetupErrors", members: &["StandardOutputHandleError", "StandardOutputCapabilityError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "AnsiRenderErrors", members: &["StandardOutputHandleError", "StandardOutputCapabilityError", "WriteFailureError", "FlushFailureError", "TerminalWriteFailureError", "InvalidCursorPositionError", "SinkClosedError",], warning_eligible: true, specificity_rank: 2 },
    StdlibErrorFamily { name: "ConsoleIoErrors", members: &["StandardInputReadError", "StandardOutputHandleError", "StandardOutputCapabilityError", "WriteFailureError", "FlushFailureError", "TerminalWriteFailureError", "InvalidCursorPositionError", "SinkClosedError",], warning_eligible: false, specificity_rank: 3 },
    StdlibErrorFamily { name: "SleepErrors", members: &["InvalidDurationError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "FrameClockErrors", members: &["InvalidFrameRateError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "TimeErrors", members: &["InvalidDurationError", "InvalidFrameRateError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "MonotonicTimerErrors", members: &["MonotonicTimerError", "MonotonicTimerNotArmedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ClockErrors", members: &["InvalidDurationError", "InvalidFrameRateError", "MonotonicTimerError", "MonotonicTimerNotArmedError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "FilesystemPathErrors", members: &["InvalidPathError", "PermissionDeniedError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemExistenceErrors", members: &["PermissionDeniedError", "InvalidPathError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemRawReadErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemTextReadErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError", "InvalidUtf8Error",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemOffsetReadErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "OffsetOutOfRangeError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemLineReadErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidUtf8Error", "OffsetOutOfRangeError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemReadErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError", "InvalidUtf8Error", "OffsetOutOfRangeError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "FilesystemOverwriteErrors", members: &["PermissionDeniedError", "WriteFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemAppendErrors", members: &["FileNotFoundError", "PermissionDeniedError", "WriteFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemOffsetWriteErrors", members: &["FileNotFoundError", "PermissionDeniedError", "WriteFailureError", "OffsetOutOfRangeError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemWriteErrors", members: &["FileNotFoundError", "PermissionDeniedError", "WriteFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError", "OffsetOutOfRangeError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "FilesystemCreateErrors", members: &["FileAlreadyExistsError", "PermissionDeniedError", "CreateFailureError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemDeleteErrors", members: &["FileNotFoundError", "PermissionDeniedError", "DeleteFailureError", "IsADirectoryError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemDirectoryDeleteErrors", members: &["DirectoryNotFoundError", "PermissionDeniedError", "DeleteFailureError", "DirectoryNotEmptyError", "IsNotADirectoryError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemCopyErrors", members: &["FileNotFoundError", "PermissionDeniedError", "CopyFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemMoveErrors", members: &["FileNotFoundError", "PermissionDeniedError", "MoveFailureError", "FileAlreadyExistsError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemCopyMoveErrors", members: &["FileNotFoundError", "PermissionDeniedError", "CopyFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError", "MoveFailureError", "FileAlreadyExistsError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "FilesystemMetadataErrors", members: &["FileNotFoundError", "PermissionDeniedError", "MetadataUnavailableError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemListErrors", members: &["DirectoryNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsNotADirectoryError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemDirectoryCreateErrors", members: &["FileAlreadyExistsError", "PermissionDeniedError", "CreateFailureError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemRecursiveDirectoryCreateErrors", members: &["PermissionDeniedError", "CreateFailureError", "InvalidPathError", "FilesystemFullError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemPermissionErrors", members: &["PermissionDeniedError", "SetPermissionsError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "FilesystemMutationErrors", members: &["FileNotFoundError", "PermissionDeniedError", "WriteFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError", "OffsetOutOfRangeError", "FileAlreadyExistsError", "CreateFailureError", "DeleteFailureError", "DirectoryNotFoundError", "DirectoryNotEmptyError", "IsNotADirectoryError", "CopyFailureError", "MoveFailureError", "SetPermissionsError",], warning_eligible: false, specificity_rank: 2 },
    StdlibErrorFamily { name: "FilesystemErrors", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError", "InvalidUtf8Error", "OffsetOutOfRangeError", "WriteFailureError", "FilesystemFullError", "FileAlreadyExistsError", "CreateFailureError", "DeleteFailureError", "DirectoryNotFoundError", "DirectoryNotEmptyError", "IsNotADirectoryError", "CopyFailureError", "MoveFailureError", "MetadataUnavailableError", "LineOutOfRangeError", "SetPermissionsError",], warning_eligible: false, specificity_rank: 3 },
    StdlibErrorFamily { name: "ProcessCurrentDirectoryErrors", members: &["PermissionDeniedError", "InvalidPathError", "CurrentWorkingDirectoryUnavailableError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessExecutablePathErrors", members: &["PermissionDeniedError", "InvalidPathError", "CurrentExecutablePathUnavailableError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessSetDirectoryErrors", members: &["FileNotFoundError", "PermissionDeniedError", "IsNotADirectoryError", "InvalidPathError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessPathErrors", members: &["PermissionDeniedError", "InvalidPathError", "CurrentWorkingDirectoryUnavailableError", "CurrentExecutablePathUnavailableError", "FileNotFoundError", "IsNotADirectoryError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "EnvironmentLookupErrors", members: &["EnvironmentVariableNotFoundError", "InvalidEnvironmentVariableNameError", "InvalidUtf8Error",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "EnvironmentOptionalLookupErrors", members: &["InvalidEnvironmentVariableNameError", "InvalidUtf8Error"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "EnvironmentProbeErrors", members: &["InvalidEnvironmentVariableNameError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessEnvErrors", members: &["EnvironmentVariableNotFoundError", "InvalidEnvironmentVariableNameError", "InvalidUtf8Error",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "ProcessErrors", members: &["PermissionDeniedError", "InvalidPathError", "CurrentWorkingDirectoryUnavailableError", "CurrentExecutablePathUnavailableError", "FileNotFoundError", "IsNotADirectoryError", "EnvironmentVariableNotFoundError", "InvalidEnvironmentVariableNameError", "InvalidUtf8Error",], warning_eligible: false, specificity_rank: 2 },
    StdlibErrorFamily { name: "SystemWaitSetErrors", members: &["SystemWaitSetError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "SystemWaitRegistrationErrors", members: &["SystemWaitSetError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessControlOpenErrors", members: &["ProcessControlUnavailableError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessControlPollErrors", members: &["ProcessControlError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessControlAckErrors", members: &["ProcessControlAcknowledgementError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessControlResumeErrors", members: &["ProcessControlResumeError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ProcessControlErrors", members: &["ProcessControlUnavailableError", "ProcessControlError", "ProcessControlAcknowledgementError", "ProcessControlResumeError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "TerminalSessionOpenErrors", members: &["TerminalSessionOptionsError", "TerminalSessionOpenError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionReadErrors", members: &["TerminalSessionReadError", "TerminalSessionStateError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionWriteErrors", members: &["TerminalSessionWriteError", "TerminalSessionStateError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionCursorErrors", members: &["TerminalSessionWriteError", "TerminalSessionStateError", "InvalidCursorPositionError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionRestoreErrors", members: &["TerminalSessionRestoreError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionPauseResumeErrors", members: &["TerminalSessionOpenError", "TerminalSessionRestoreError", "TerminalSessionStateError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalSessionLifecycleErrors", members: &["TerminalSessionOptionsError", "TerminalSessionOpenError", "TerminalSessionRestoreError", "TerminalSessionStateError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "TerminalSessionRenderErrors", members: &["TerminalSessionWriteError", "TerminalSessionStateError", "InvalidCursorPositionError", "TerminalTextLayoutError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "TerminalSessionErrors", members: &["TerminalSessionOptionsError", "TerminalSessionOpenError", "TerminalSessionReadError", "TerminalSessionWriteError", "TerminalSessionStateError", "TerminalSessionRestoreError", "InvalidCursorPositionError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 2 },
    StdlibErrorFamily { name: "TerminalTestingErrors", members: &["TerminalTestFactoryError", "ConstraintViolationError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalChordValidationErrors", members: &["TerminalChordValidationError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalChordMutationErrors", members: &["TerminalChordMutationError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalChordReplaceErrors", members: &["TerminalChordValidationError", "TerminalChordMutationError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 1 },
    StdlibErrorFamily { name: "TerminalChordProcessErrors", members: &["TerminalChordProcessError", "AllocationFailureError"], warning_eligible: true, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalChordReleasedInputErrors", members: &["IndexOutOfBoundsError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "TerminalChordRouterErrors", members: &["TerminalChordValidationError", "TerminalChordMutationError", "TerminalChordProcessError", "IndexOutOfBoundsError", "ConstraintViolationError", "AllocationFailureError",], warning_eligible: true, specificity_rank: 2 },
    StdlibErrorFamily { name: "ErrorCauseInspectionErrors", members: &["ErrorAttachmentAbsentError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ErrorSuppressedInspectionErrors", members: &["IndexOutOfBoundsError"], warning_eligible: false, specificity_rank: 0 },
    StdlibErrorFamily { name: "ErrorInspectionErrors", members: &["ErrorAttachmentAbsentError", "IndexOutOfBoundsError"], warning_eligible: true, specificity_rank: 0 },
    // Singular compatibility aliases retained for existing source.
    StdlibErrorFamily { name: "ParseError", members: &["ParseError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "BytesError", members: &["HexDecodeError", "SliceRangeError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StringSearchError", members: &["StringEmptySearchTextError", "StringPatternNotFoundError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StringRangeError", members: &["StringNegativeCountError", "StringRangeOutOfBoundsError", "StringRangeOrderError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StringBuilderError", members: &["BuilderFinishedError", "AllocationFailureError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "OutputError", members: &["WriteFailureError", "FlushFailureError", "SinkClosedError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StandardInputReadError", members: &["StandardInputReadError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StandardOutputHandleError", members: &["StandardOutputHandleError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "StandardOutputCapabilityError", members: &["StandardOutputCapabilityError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "TerminalError", members: &["TerminalWriteFailureError", "InvalidCursorPositionError", "SinkClosedError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "TimeError", members: &["InvalidDurationError", "InvalidFrameRateError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "ProcessPathError", members: &["PermissionDeniedError", "InvalidPathError", "CurrentWorkingDirectoryUnavailableError", "CurrentExecutablePathUnavailableError", "FileNotFoundError", "IsNotADirectoryError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "ProcessEnvError", members: &["EnvironmentVariableNotFoundError", "InvalidEnvironmentVariableNameError", "InvalidUtf8Error",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemPathError", members: &["InvalidPathError", "PermissionDeniedError"], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemReadError", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError", "InvalidUtf8Error", "OffsetOutOfRangeError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemWriteError", members: &["FileNotFoundError", "PermissionDeniedError", "WriteFailureError", "IsADirectoryError", "InvalidPathError", "FilesystemFullError", "OffsetOutOfRangeError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemCreateError", members: &["FileAlreadyExistsError", "PermissionDeniedError", "CreateFailureError", "InvalidPathError", "FilesystemFullError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemDeleteError", members: &["FileNotFoundError", "PermissionDeniedError", "DeleteFailureError", "IsADirectoryError", "InvalidPathError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemDirectoryDeleteError", members: &["DirectoryNotFoundError", "PermissionDeniedError", "DeleteFailureError", "DirectoryNotEmptyError", "IsNotADirectoryError", "InvalidPathError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemCopyMoveError", members: &["FileNotFoundError", "PermissionDeniedError", "CopyFailureError", "MoveFailureError", "IsADirectoryError", "FileAlreadyExistsError", "InvalidPathError", "FilesystemFullError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemMetadataError", members: &["FileNotFoundError", "PermissionDeniedError", "MetadataUnavailableError", "InvalidPathError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemListError", members: &["DirectoryNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsNotADirectoryError", "InvalidPathError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "FilesystemError", members: &["FileNotFoundError", "PermissionDeniedError", "ReadFailureError", "IsADirectoryError", "InvalidPathError", "InvalidUtf8Error", "OffsetOutOfRangeError", "WriteFailureError", "FilesystemFullError", "FileAlreadyExistsError", "CreateFailureError", "DeleteFailureError", "DirectoryNotFoundError", "DirectoryNotEmptyError", "IsNotADirectoryError", "CopyFailureError", "MoveFailureError", "MetadataUnavailableError", "LineOutOfRangeError", "SetPermissionsError",], warning_eligible: false, specificity_rank: 50 },
    StdlibErrorFamily { name: "IndexAccessError", members: &["IndexOutOfBoundsError"], warning_eligible: false, specificity_rank: 50 },
];
